// TODO native review: all French and Arabic strings in this table.
export const extraMessages=[
['VERSION 0.4','VERSION 0.4','الإصدار 0.4'],
['Continue','Continuer','متابعة'],['Ready to Play','Prêt à jouer','جاهز للعب'],['Choose where you will fight.','Choisissez votre terrain de combat.','اختر ساحة القتال.'],['Choose how long you want to survive.','Choisissez la durée de votre partie.','اختر مدة الجولة.'],['Choose your attack controls, then start your run.','Choisissez vos commandes d’attaque, puis lancez la partie.','اختر نمط الهجوم ثم ابدأ الجولة.'],['STAMINA','ENDURANCE','التحمل'],['Stamina','Endurance','التحمل'],['min','min','دقيقة'],['Narration: English male voice','Narration : voix masculine anglaise','السرد: صوت رجل بالإنجليزية'],
['Enemies defeated','Ennemis vaincus','الأعداء المهزومون'],
['Survival','Survie','البقاء'],['10 min','10 min','١٠ دقائق'],['20 min','20 min','٢٠ دقيقة'],['Equipment:','Équipement :','المعدات:'],['{name} defeated the final boss!','{name} a vaincu le boss final !','هزم {name} الزعيم الأخير!'],['{name} earned {n} cacao.','{name} a gagné {n} cacao.','جمع {name} عدد {n} من الكاكاو.'],
['The World','L’univers','عالم اللعبة'],['Heroes','Héros','الأبطال'],['Combat','Combat','القتال'],['Currency & Upgrades','Monnaie et améliorations','العملة والترقيات'],['Equipment','Équipement','المعدات'],['Accessibility','Accessibilité','إمكانية الوصول'],['Controls, progression, and world background.','Commandes, progression et univers du jeu.','التحكم والتقدم وخلفية عالم اللعبة.'],
['A fantasy adventure inspired by Maya cities, astronomy, trade, and mythology. The heroes and invasion are fictional.','Une aventure fantastique inspirée des cités, de l’astronomie, du commerce et des mythes mayas. Les héros et l’invasion sont fictifs.','مغامرة خيالية مستوحاة من مدن المايا وفلكهم وتجارتهم وأساطيرهم. الأبطال والغزو من الخيال.'],
['Balam fights in melee. Ixchel uses mana-based magic. Kukul fires piercing darts. Each hero has 20 skills; equip up to three per run.','Balam combat au corps à corps. Ixchel utilise la magie et le mana. Kukul tire des traits perforants. Chaque héros possède 20 compétences ; équipez-en trois par partie.','يقاتل بالام في الاشتباك القريب، وتستخدم إيشيل سحر المانا، ويطلق كوكول مقذوفات خارقة. لكل بطل ٢٠ مهارة؛ جهّز ثلاثًا في الجولة.'],
['Choose auto-attack or manual attack in Settings. Move to avoid enemies, collect XP, and pick upgrades. At level 5, a permanent AI ally joins you and tougher enemies enter the waves. Melee heroes face ground enemies and ground-based bosses.','Choisissez l’attaque auto ou manuelle dans les options. Évitez les ennemis, ramassez l’XP et choisissez des améliorations. Au niveau 5, un allié IA permanent vous rejoint et des ennemis plus forts apparaissent. Les héros de mêlée affrontent des ennemis et des boss terrestres.','اختر الهجوم التلقائي أو اليدوي من الإعدادات. تفادَ الأعداء واجمع الخبرة واختر الترقيات. عند المستوى ٥ ينضم رفيق دائم يتحكم به الذكاء الاصطناعي وتظهر أعداء أقوى. يواجه أبطال الاشتباك القريب أعداء وزعماء أرضيين.'],
['Cacao is earned during runs and kept after defeat. Spend it on permanent upgrades. Break pots and baskets to find extra supplies.','Le cacao gagné reste acquis après une défaite. Dépensez-le en améliorations permanentes. Brisez les pots et paniers pour trouver des ressources.','تحتفظ بالكاكاو المكتسب حتى بعد الهزيمة. أنفقه على ترقيات دائمة. حطّم الأواني والسلال للعثور على إمدادات إضافية.'],
['Mini-bosses drop equipment and offer skill upgrades. Equipment lasts for the current run; permanent upgrades are bought in the main menu.','Les mini-boss donnent de l’équipement et des compétences. L’équipement dure une partie ; les améliorations permanentes s’achètent depuis le menu principal.','يسقط الزعماء الفرعيون معدات ويمنحون ترقيات مهارات. تدوم المعدات طوال الجولة؛ وتُشترى الترقيات الدائمة من القائمة الرئيسية.'],
['Touch and keyboard controls are supported. Aim assist, manual attacks, reduced effects, a 30 FPS mode, and separate audio sliders are available in Settings.','Le tactile et le clavier sont pris en charge. Aide à la visée, attaque manuelle, effets réduits, mode 30 images/s et réglages audio sont disponibles dans les options.','تدعم اللعبة اللمس ولوحة المفاتيح. تتوفر مساعدة التصويب والهجوم اليدوي وتقليل المؤثرات ونمط ٣٠ إطارًا/ث ومستويات صوت مستقلة في الإعدادات.'],
['Cosmetics and downloadable extras. No paid stat boosts.','Cosmétiques et contenus à télécharger. Aucun bonus de puissance payant.','مظاهر وإضافات قابلة للتنزيل. لا تُباع ترقيات القوة.'],['Preview build: purchases are not enabled. Cosmetic items below are planned, not usable unlocks.','Version de test : achats désactivés. Les cosmétiques ci-dessous sont prévus, mais pas encore utilisables.','نسخة تجريبية: الشراء غير مفعّل. المظاهر أدناه مخطط لها وليست قابلة للاستخدام حاليًا.'],['Preview offering','Aperçu','معاينة'],['Roadmap item','À venir','قادم لاحقًا'],['Included in launch plan','Prévu pour plus tard','مخطط لاحقًا'],['Planned','Prévu','مخطط'],
["Founder's Jaguar Mantle",'Tenue jaguar du fondateur','رداء الجاغوار للمؤسس'],['Quetzal Trail Collection','Traînées du quetzal','آثار الكيتزال'],['Codex & Original Soundtrack','Art et bande originale','كتاب الرسومات والموسيقى'],['Lords of Xibalba Expansion','Extension Seigneurs de Xibalba','توسعة أسياد شيبالبا'],
['A ceremonial gold-and-obsidian Balam skin, jade trail, and founder profile crest. Cosmetic only.','Une tenue dorée pour Balam, une traînée de jade et un emblème de fondateur. Cosmétique uniquement.','مظهر ذهبي لبالام وأثر يشم وشعار للمؤسس. عناصر تجميلية فقط.'],['Three colorful dash trails shared by every champion. Cosmetic only.','Trois traînées d’esquive colorées pour tous les héros. Cosmétique uniquement.','ثلاثة آثار اندفاع ملونة لجميع الأبطال. عناصر تجميلية فقط.'],['High-resolution art, development codex, and the full original soundtrack as downloadable extras.','Illustrations haute résolution, carnet de développement et bande originale complète à télécharger.','رسومات عالية الدقة ودليل تطوير والموسيقى الأصلية الكاملة للتنزيل.'],['A future paid content expansion with maps, story chapters, and new champions—never stat boosts.','Une future extension payante avec des cartes, des chapitres et des héros, jamais de bonus de statistiques.','توسعة مستقبلية مدفوعة بخرائط وفصول وأبطال جدد، دون زيادات مدفوعة للإحصاءات.']
];
