// Generated by scripts/generate-skill-i18n.mjs; edit skill-descriptions.js for translations.
// Names and English descriptions are copied verbatim from skills_redesign.json.
export const skillMessages = [
 ["Jaguar's Roar","Rugissement du jaguar","زئير الجاغوار"], // TODO native review
 ["A terrifying roar hurts nearby foes and makes them flee for 2 seconds.","Un rugissement blesse les ennemis proches et les fait fuir 2 secondes.","زئير مرعب يؤذي الأعداء القريبين ويجعلهم يفرون لمدة 2 ثانية."], // TODO native review
 ["Obsidian Arc","Arc d'obsidienne","قوس السبج"], // TODO native review
 ["A black-glass slash cleaves a wide arc and leaves enemies bleeding.","Une entaille d’obsidienne balaie un large arc et fait saigner les ennemis.","ضربة من السبج تشق قوسا واسعا وتسبب نزيف الأعداء."], // TODO native review
 ["Prowler's Leap","Bond du prédateur","وثبة المفترس"], // TODO native review
 ["Leap onto the nearest enemy and land with a shockwave.","Bondissez sur l’ennemi le plus proche et atterrissez avec une onde de choc.","اقفز على أقرب عدو واهبط بموجة صادمة."], // TODO native review
 ["Claw Cyclone","Cyclone de griffes","إعصار المخالب"], // TODO native review
 ["Spin in a whirlwind of claws, shredding everything around you.","Tourbillonnez en lacérant de vos griffes tout ce qui vous entoure.","در في دوامة من المخالب تمزق كل ما حولك."], // TODO native review
 ["Ceiba Breaker","Briseur de ceiba","محطم السيبا"], // TODO native review
 ["Smash the nearest enemy with a ceiba log, stunning it.","Écrasez l’ennemi le plus proche avec un tronc de ceiba pour l’étourdir.","اضرب أقرب عدو بجذع السيبا لتصعقه."], // TODO native review
 ["Bloodless Hunt","Chasse spectrale","الصيد الطيفي"], // TODO native review
 ["A spectral fang hunts down the healthiest enemy on screen.","Un croc spectral traque l’ennemi qui a le plus de vie à l’écran.","ناب طيفي يطارد العدو صاحب أعلى صحة على الشاشة."], // TODO native review
 ["Stone Maw","Mâchoire de pierre","فك الحجر"], // TODO native review
 ["Plant a stone jaw that snaps shut on the first enemies to step near it.","Posez une mâchoire de pierre qui se referme sur les premiers ennemis proches.","ازرع فكا حجريا ينطبق على أول الأعداء الذين يقتربون منه."], // TODO native review
 ["War Drum","Tambour de guerre","طبل الحرب"], // TODO native review
 ["Beat a war drum: pulses damage foes and quicken your attacks.","Battez le tambour : ses pulsations blessent les ennemis et accélèrent vos attaques.","اقرع طبل الحرب: نبضاته تؤذي الأعداء وتسرع هجماتك."], // TODO native review
 ["Sun Claw","Griffe solaire","مخلب الشمس"], // TODO native review
 ["Four golden claw slashes burn everything around you.","Quatre griffes dorées brûlent tout autour de vous.","أربع ضربات بمخالب ذهبية تحرق كل ما حولك."], // TODO native review
 ["Jaguar Echo","Écho du jaguar","صدى الجاغوار"], // TODO native review
 ["A spectral jaguar chases and pounces on enemies for you.","Un jaguar spectral poursuit les ennemis et bondit sur eux pour vous.","جاغوار طيفي يطارد الأعداء وينقض عليهم نيابة عنك."], // TODO native review
 ["Fang Path","Chemin des crocs","طريق الأنياب"], // TODO native review
 ["Jade fangs burst from the earth in a line and slow what they hit.","Des crocs de jade jaillissent en ligne du sol et ralentissent leurs cibles.","تنبثق أنياب اليشم من الأرض في خط وتبطئ من تصيبه."], // TODO native review
 ["Hunter's Mark","Marque du chasseur","علامة الصياد"], // TODO native review
 ["Mark the 3 most dangerous enemies. They take extra damage.","Marquez les 3 ennemis les plus dangereux. Ils subissent plus de dégâts.","ضع علامة على أخطر 3 أعداء ليصبح الضرر الذي يتلقونه أكبر."], // TODO native review
 ["Nine Lives","Neuf vies","تسع أرواح"], // TODO native review
 ["Heal instantly and sprint away on spirit paws.","Soignez-vous aussitôt et filez sur des pattes spectrales.","استعد صحتك فورا وانطلق بسرعة على قوائم طيفية."], // TODO native review
 ["Black Mirror","Miroir noir","المرآة السوداء"], // TODO native review
 ["Raise an obsidian mirror that throws enemy shots back at them.","Dressez un miroir d’obsidienne qui renvoie les tirs aux ennemis.","ارفع مرآة من السبج تعكس مقذوفات الأعداء نحوهم."], // TODO native review
 ["Pyramid Rush","Charge de la pyramide","اندفاعة الهرم"], // TODO native review
 ["Charge forward like a falling temple, shoving everything aside.","Chargez tel un temple qui s’effondre et repoussez tout sur votre passage.","اندفع كالمعبد المنهار وادفع كل ما يعترض طريقك جانبا."], // TODO native review
 ["Heart of Balam","Coeur de Balam","قلب بالام"], // TODO native review
 ["A golden ward protects you, then bursts into a roar when it ends.","Un bouclier doré vous protège puis éclate en rugissant à son terme.","درع ذهبي يحميك ثم ينفجر بزئير عند انتهائه."], // TODO native review
 ["Bloodlust","Soif de sang","عطش الدم"], // TODO native review
 ["Every kill grants stacking attack speed for a short time.","Chaque ennemi tué cumule brièvement de la vitesse d’attaque.","كل قتلة تمنح زيادة متراكمة في سرعة الهجوم لفترة قصيرة."], // TODO native review
 ["Stonehide","Peau de pierre","جلد الحجر"], // TODO native review
 ["The more wounded you are, the harder your skin becomes.","Plus vous êtes blessé, plus votre peau durcit.","كلما اشتدت جراحك ازدادت صلابة جلدك."], // TODO native review
 ["Predator's Rhythm","Rythme du prédateur","إيقاع المفترس"], // TODO native review
 ["Critical hits shorten the cooldowns of your skills.","Les coups critiques réduisent la recharge de vos compétences.","الضربات الحرجة تقلل مدة انتظار مهاراتك."], // TODO native review
 ["Feast of the Fallen","Festin des vaincus","وليمة الساقطين"], // TODO native review
 ["Every 12 kills restore a chunk of your health.","Tous les 12 ennemis tués, récupérez une partie de votre vie.","كل 12 قتلة تستعيد جزءا من صحتك."], // TODO native review
 ["Obsidian Thorns","Épines d'obsidienne","أشواك السبج"], // TODO native review
 ["Enemies that hit you in melee are cut by obsidian spikes.","Des pointes d’obsidienne blessent les ennemis qui vous frappent en mêlée.","أشواك السبج تجرح الأعداء الذين يضربونك في الاشتباك القريب."], // TODO native review
 ["Jaguar's Pride","Fierté du jaguar","كبرياء الجاغوار"], // TODO native review
 ["You fight better when surrounded.","Vous combattez mieux quand vous êtes encerclé.","تقاتل بقوة أكبر عندما تكون محاصرا."], // TODO native review
 ["Earthshaker","Briseur de terre","مزلزل الأرض"], // TODO native review
 ["Every 4th basic attack slams the ground.","Chaque 4e attaque de base frappe le sol.","كل هجمة أساسية رابعة تضرب الأرض."], // TODO native review
 ["Wounded Fury","Fureur blessée","غضب الجريح"], // TODO native review
 ["Below half health you hit harder and steal life.","Sous la moitié de votre vie, vos coups sont plus forts et volent de la vie.","دون نصف صحتك، تضرب بقوة أكبر وتسرق الصحة."], // TODO native review
 ["Copal Star","Étoile de copal","نجمة الكوبال"], // TODO native review
 ["A slow jade star pierces enemies and leaves slowing copal smoke.","Une étoile de jade lente transperce les ennemis et laisse une fumée qui ralentit.","نجمة يشم بطيئة تخترق الأعداء وتترك دخان كوبال يبطئهم."], // TODO native review
 ["Jade Halo","Halo de jade","هالة اليشم"], // TODO native review
 ["Jade beads orbit you, hurting enemies and blocking enemy shots.","Des perles de jade orbitent autour de vous, blessant les ennemis et bloquant leurs tirs.","خرزات يشم تدور حولك وتؤذي الأعداء وتصد مقذوفاتهم."], // TODO native review
 ["Ancestor Flame","Flamme ancestrale","لهب الأسلاف"], // TODO native review
 ["Blue-green spirit fire leaps between up to five enemies.","Un feu spirituel bleu-vert bondit entre cinq ennemis au maximum.","نار روحية زرقاء مخضرة تقفز بين خمسة أعداء كحد أقصى."], // TODO native review
 ["Moonwell","Puits lunaire","بئر القمر"], // TODO native review
 ["Create a moon pool that slows enemies and refills your mana.","Créez un bassin lunaire qui ralentit les ennemis et régénère votre mana.","أنشئ بركة قمرية تبطئ الأعداء وتجدد المانا لديك."], // TODO native review
 ["Censer Wave","Vague d'encens","موجة البخور"], // TODO native review
 ["A wave of incense smoke shoves enemies back and confuses them.","Une vague de fumée d’encens repousse les ennemis et les désoriente.","موجة من دخان البخور تدفع الأعداء للخلف وتربكهم."], // TODO native review
 ["Verdant Mercy","Grâce verdoyante","رحمة الطبيعة"], // TODO native review
 ["Grow a glade that heals you and your ally while you stand in it.","Faites pousser une clairière qui vous soigne, vous et votre allié, à l’intérieur.","أنبت فسحة تشفيك أنت ورفيقك ما دمتما داخلها."], // TODO native review
 ["Copal Veil","Voile de copal","حجاب الكوبال"], // TODO native review
 ["A smoke veil absorbs damage and turns part of it into mana.","Un voile de fumée absorbe les dégâts et en transforme une partie en mana.","حجاب من الدخان يمتص الضرر ويحول جزءا منه إلى مانا."], // TODO native review
 ["Glyph Comet","Comète de glyphes","مذنب الرموز"], // TODO native review
 ["A jade comet crashes down a line and scorches glowing glyphs into the ground.","Une comète de jade frappe en ligne et grave des glyphes brûlants dans le sol.","مذنب يشم يندفع في خط وينقش رموزا متوهجة تحرق الأرض."], // TODO native review
 ["Cacao Bloom","Floraison de cacao","إزهار الكاكاو"], // TODO native review
 ["Cacao flowers burst under nearby enemies, poisoning them.","Des fleurs de cacao éclatent sous les ennemis proches et les empoisonnent.","تتفجر زهور الكاكاو تحت الأعداء القريبين وتسممهم."], // TODO native review
 ["Raincaller","Invocatrice de pluie","داعية المطر"], // TODO native review
 ["Call a storm cloud that follows enemy groups and strikes them with lightning.","Invoquez un nuage d’orage qui suit les groupes ennemis et les foudroie.","استدع سحابة عاصفة تتبع مجموعات الأعداء وتصعقهم بالبرق."], // TODO native review
 ["Spirit Familiar","Familier spirituel","الرفيق الروحي"], // TODO native review
 ["A hummingbird spirit darts at enemies and feeds you mana.","Un colibri spirituel fond sur les ennemis et vous rend du mana.","روح طائر طنان تنقض على الأعداء وتعيد لك المانا."], // TODO native review
 ["Serpent Coil","Étreinte du serpent","التفاف الأفعى"], // TODO native review
 ["A spectral serpent drags enemies together and crushes them.","Un serpent spectral rassemble les ennemis et les écrase.","أفعى طيفية تسحب الأعداء معا وتسحقهم."], // TODO native review
 ["Jade Needles","Aiguilles de jade","إبر اليشم"], // TODO native review
 ["Needles stick in enemies and shatter a moment later.","Des aiguilles se plantent dans les ennemis puis éclatent peu après.","إبر تنغرس في الأعداء وتتحطم بعد لحظة."], // TODO native review
 ["Dreamwalk","Marche onirique","سير الأحلام"], // TODO native review
 ["Slip into the spirit world, walk through enemies, and return with a shockwave.","Entrez dans le monde des esprits, traversez les ennemis et revenez avec une onde de choc.","ادخل عالم الأرواح واعبر الأعداء ثم عد بموجة صادمة."], // TODO native review
 ["Four Directions","Quatre directions","الاتجاهات الأربعة"], // TODO native review
 ["Four sacred bolts shoot north, east, south and west.","Quatre traits sacrés partent au nord, à l’est, au sud et à l’ouest.","أربعة مقذوفات مقدسة تنطلق شمالا وشرقا وجنوبا وغربا."], // TODO native review
 ["Ixchel's Mantle","Manteau d'Ixchel","عباءة إكشيل"], // TODO native review
 ["Wrap yourself in moonlight: more mana, cheaper spells.","Drapez-vous de clair de lune : plus de mana, des sorts moins coûteux.","تلفع بضوء القمر: مانا أكثر وتعاويذ أقل تكلفة."], // TODO native review
 ["Ancestral Echo","Écho ancestral","صدى الأسلاف"], // TODO native review
 ["Every 5th basic attack chains to nearby enemies.","Chaque 5e attaque de base rebondit vers les ennemis proches.","كل هجمة أساسية خامسة تتسلسل إلى الأعداء القريبين."], // TODO native review
 ["Mana Spring","Source de mana","ينبوع المانا"], // TODO native review
 ["Every 15 kills refill a part of your mana.","Tous les 15 ennemis tués, récupérez une partie de votre mana.","كل 15 قتلة تستعيد جزءا من المانا."], // TODO native review
 ["Lunar Boon","Faveur lunaire","نعمة القمر"], // TODO native review
 ["Every 20 seconds your next skill is free and stronger.","Toutes les 20 secondes, votre prochaine compétence est gratuite et renforcée.","كل 20 ثانية تصبح مهارتك التالية مجانية وأقوى."], // TODO native review
 ["Rooted Meditation","Méditation enracinée","التأمل المتجذر"], // TODO native review
 ["Stand still to channel the world tree.","Restez immobile pour puiser la force de l’arbre-monde.","قف ثابتا لتستمد قوة شجرة العالم."], // TODO native review
 ["Jade Resilience","Résilience de jade","صلابة اليشم"], // TODO native review
 ["If nothing hurts you, a jade shield slowly builds up.","Un bouclier de jade se forme peu à peu tant que vous ne subissez aucun dégât.","يتكون درع يشم تدريجيا ما دمت لا تتلقى ضررا."], // TODO native review
 ["Spirit Harvest","Moisson des esprits","حصاد الأرواح"], // TODO native review
 ["Defeated enemies sometimes release a healing wisp.","Les ennemis vaincus libèrent parfois une lueur qui soigne.","يطلق الأعداء المهزومون أحيانا روحا مضيئة تشفيك."], // TODO native review
 ["Crescent Blessing","Bénédiction du croissant","بركة الهلال"], // TODO native review
 ["Critical hits restore mana.","Les coups critiques rendent du mana.","الضربات الحرجة تستعيد المانا."], // TODO native review
 ["Mana Overflow","Trop-plein de mana","فيض المانا"], // TODO native review
 ["A full reservoir of mana powers your spells.","Une réserve de mana pleine renforce vos sorts.","مخزون مانا ممتلئ يقوي تعاويذك."], // TODO native review
 ["Atlatl Volley","Volée d'atlatl","وابل الأتلاتل"], // TODO native review
 ["A tight fan of five piercing darts.","Un éventail serré de cinq traits perforants.","وابل متقارب من خمسة مقذوفات خارقة."], // TODO native review
 ["Featherstorm","Tempête de plumes","عاصفة الريش"], // TODO native review
 ["A storm of obsidian feathers drifts forward, shredding enemies.","Une tempête de plumes d’obsidienne avance en lacérant les ennemis.","عاصفة من ريش السبج تتقدم وتمزق الأعداء."], // TODO native review
 ["Serpent Path","Sentier du serpent","درب الأفعى"], // TODO native review
 ["A jade serpent weaves through a line of enemies.","Un serpent de jade ondule à travers une ligne d’ennemis.","أفعى يشم تتلوى عبر صف من الأعداء."], // TODO native review
 ["Windstep","Pas du vent","خطوة الريح"], // TODO native review
 ["Dash through danger leaving a cutting wind trail.","Esquivez le danger en laissant un sillage de vent tranchant.","اندفع عبر الخطر تاركا خلفك أثرا من الرياح القاطعة."], // TODO native review
 ["Quetzal Flip","Saut du quetzal","قفزة الكيتزال"], // TODO native review
 ["Flip away from danger while firing back.","Bondissez loin du danger en tirant derrière vous.","اقفز بعيدا عن الخطر وأطلق النار خلفك."], // TODO native review
 ["Hunter's Snare","Filet du chasseur","شبكة الصياد"], // TODO native review
 ["Throw a woven net that roots enemies in place.","Lancez un filet tressé qui immobilise les ennemis.","ارم شبكة منسوجة تثبت الأعداء في أماكنهم."], // TODO native review
 ["Eagle Eye","Oeil d'aigle","عين النسر"], // TODO native review
 ["Hold still, focus, and fire a guaranteed critical shot.","Restez immobile, visez et tirez un coup critique garanti.","قف ثابتا وركز ثم أطلق ضربة حرجة مضمونة."], // TODO native review
 ["Sun Dart","Fléchette solaire","سهم الشمس"], // TODO native review
 ["A golden dart bounces between enemies, hitting harder each time.","Un trait doré rebondit entre les ennemis, plus puissant à chaque rebond.","مقذوف ذهبي يرتد بين الأعداء وتزداد قوته مع كل ارتداد."], // TODO native review
 ["Storm Nest","Nid de tempête","عش العاصفة"], // TODO native review
 ["A feather nest that shoots wind darts at three enemies at once.","Un nid de plumes tire des traits de vent sur trois ennemis à la fois.","عش من الريش يطلق سهام الريح على ثلاثة أعداء في آن واحد."], // TODO native review
 ["Plume Guard","Garde de plumes","حارس الريش"], // TODO native review
 ["Three feathers block the next three hits.","Trois plumes bloquent les trois prochains coups.","ثلاث ريشات تصد الضربات الثلاث التالية."], // TODO native review
 ["Cacao Bomb","Bombe de cacao","قنبلة الكاكاو"], // TODO native review
 ["Lob a clay cacao bomb that explodes with beans.","Lancez une bombe de cacao en argile qui explose en projetant des fèves.","ارم قنبلة كاكاو طينية تنفجر وتنثر الحبوب."], // TODO native review
 ["Forked Flight","Vol fourchu","الطيران المتشعب"], // TODO native review
 ["One dart splits into three that each hunt a different target.","Un trait se divise en trois, chacun traquant une cible différente.","مقذوف واحد ينقسم إلى ثلاثة يطارد كل منها هدفا مختلفا."], // TODO native review
 ["Gale Ring","Anneau de bourrasque","حلقة العاصفة"], // TODO native review
 ["A wind ring blasts enemies away and speeds you up.","Un anneau de vent repousse les ennemis et vous accélère.","حلقة رياح تقذف الأعداء بعيدا وتزيد سرعتك."], // TODO native review
 ["Hunter's Trance","Transe du chasseur","نشوة الصياد"], // TODO native review
 ["Enter a trance: faster, more critical, and darts curve toward targets.","Entrez en transe : vitesse, critiques accrus et traits guidés vers les cibles.","ادخل في نشوة: سرعة وضربات حرجة أكثر ومقذوفات تتجه نحو الأهداف."], // TODO native review
 ["Skyfall","Chute du ciel","سقوط السماء"], // TODO native review
 ["A rain of heavy darts falls over a wide area.","Une pluie de traits lourds s’abat sur une vaste zone.","مطر من المقذوفات الثقيلة يهطل على منطقة واسعة."], // TODO native review
 ["Kukulkan's Breath","Souffle de Kukulkan","نفس كوكولكان"], // TODO native review
 ["Channel a feathered-serpent beam through a line of enemies.","Canalisez le rayon du serpent à plumes à travers une ligne d’ennemis.","وجه شعاع الأفعى المريشة عبر صف من الأعداء."], // TODO native review
 ["Sharpened Flint","Silex aiguisé","صوان مسنن"], // TODO native review
 ["Your projectiles pierce more enemies.","Vos projectiles transpercent plus d’ennemis.","مقذوفاتك تخترق أعداء أكثر."], // TODO native review
 ["Venomous Darts","Fléchettes venimeuses","سهام سامة"], // TODO native review
 ["Your basic darts poison enemies.","Vos traits de base empoisonnent les ennemis.","مقذوفاتك الأساسية تسمم الأعداء."], // TODO native review
 ["Full Quiver","Carquois plein","جعبة ممتلئة"], // TODO native review
 ["Every 6th shot fires a spread of darts.","Chaque 6e tir libère un éventail de traits.","كل طلقة سادسة تطلق وابلا منتشرا من المقذوفات."], // TODO native review
 ["Hunter's Focus","Concentration du chasseur","تركيز الصياد"], // TODO native review
 ["Keep hitting the same enemy to deal more damage.","Frappez sans cesse le même ennemi pour infliger plus de dégâts.","واصل ضرب العدو نفسه لإلحاق ضرر أكبر."], // TODO native review
 ["Fleet Hunter","Chasseur agile","الصياد السريع"], // TODO native review
 ["After a dash, your next shot hits much harder.","Après une esquive, votre prochain tir frappe bien plus fort.","بعد الاندفاع، تصيب طلقتك التالية بقوة أكبر بكثير."], // TODO native review
 ["Jungle Instinct","Instinct de la jungle","غريزة الغابة"], // TODO native review
 ["Sometimes you simply are not there when the hit lands.","Parfois, vous n’êtes plus là quand le coup arrive.","أحيانا تختفي ببساطة حين تصل الضربة."], // TODO native review
 ["Trophy Hunter","Chasseur de trophées","صائد الغنائم"], // TODO native review
 ["Killing a tough enemy or boss heals you and strengthens you.","Tuer un ennemi coriace ou un boss vous soigne et vous renforce.","قتل عدو قوي أو زعيم يشفيك ويزيد قوتك."], // TODO native review
 ["Steady Aim","Visée stable","تصويب ثابت"], // TODO native review
 ["Stand still to line up critical shots.","Restez immobile pour préparer des tirs critiques.","قف ثابتا لتسدد ضربات حرجة."], // TODO native review
 ["Survivor's Will","Volonté du survivant","إرادة الناجي"], // TODO native review
 ["Taking a hit makes you run faster for a moment.","Subir un coup augmente brièvement votre vitesse.","تلقي ضربة يزيد سرعتك للحظة."], // TODO native review
 ["Jade Bounty","Butin de jade","غنيمة اليشم"], // TODO native review
 ["Collecting experience gems heals you and pulls them in from afar.","Les gemmes d’expérience vous soignent et sont attirées de plus loin.","جمع جواهر الخبرة يشفيك ويجذبها من مسافة أبعد."], // TODO native review
 ["Healing Circle","Cercle de soin","دائرة الشفاء"], // TODO native review
 ["Creates a healing circle under the hero.","Crée un cercle de soin sous le héros.","تنشئ دائرة شفاء تحت البطل."], // TODO native review
 ["Jade Ward","Garde de jade","حاجز اليشم"], // TODO native review
 ["Periodically shields the hero.","Protège régulièrement le héros d’un bouclier.","تمنح البطل درعا بشكل دوري."], // TODO native review
 ["Cleansing Light","Lumière purificatrice","نور التطهير"], // TODO native review
 ["Clears enemy projectiles and removes ailments.","Dissipe les tirs ennemis et les effets néfastes.","تزيل مقذوفات الأعداء والآثار الضارة."], // TODO native review
 ["Sanctuary Dome","Dôme sanctuaire","قبة الملاذ"], // TODO native review
 ["Raises a dome that reduces damage inside.","Dresse un dôme qui réduit les dégâts à l’intérieur.","تقيم قبة تقلل الضرر داخلها."], // TODO native review
 ["Radiant Beacon","Phare radieux","المنارة المشعة"], // TODO native review
 ["Plants a beacon that makes the hero faster and more agile.","Pose une balise qui rend le héros plus rapide et agile.","تضع منارة تجعل البطل أسرع وأكثر رشاقة."], // TODO native review
 ["Lifebond","Lien de vie","رابطة الحياة"], // TODO native review
 ["Links the saintess to the hero so damage heals.","Lie la prêtresse au héros : les dégâts infligés le soignent.","تربط القديسة بالبطل فيشفيه الضرر الذي يلحقه."], // TODO native review
 ["Saving Grace","Grâce salvatrice","النعمة المنقذة"], // TODO native review
 ["Once in a while prevents a fatal blow.","Empêche un coup fatal de temps à autre.","تمنع ضربة قاتلة من حين لآخر."], // TODO native review
 ["Sacred Fervor","Ferveur sacrée","الحماسة المقدسة"], // TODO native review
 ["The saintess inspires the hero to hit harder.","La prêtresse inspire le héros à frapper plus fort.","تلهم القديسة البطل ليضرب بقوة أكبر."], // TODO native review
 ["Bulwark Wall","Mur de rempart","سور الحماية"], // TODO native review
 ["Raises a stone wall that blocks shots.","Dresse un mur de pierre qui bloque les tirs.","يقيم جدارا حجريا يصد المقذوفات."], // TODO native review
 ["War Cry","Cri de guerre","صرخة الحرب"], // TODO native review
 ["Draws enemies toward the tank.","Attire les ennemis vers le tank.","يجذب الأعداء نحو الحارس."], // TODO native review
 ["Shield Bash","Coup de bouclier","ضربة الدرع"], // TODO native review
 ["Bashes the biggest threat and stuns it.","Frappe la menace principale et l’étourdit.","يضرب أخطر عدو ويصعقه."], // TODO native review
 ["Ground Slam","Frappe du sol","ضربة الأرض"], // TODO native review
 ["Slams the ground, stunning enemies around.","Frappe le sol et étourdit les ennemis alentour.","يضرب الأرض ويصعق الأعداء المحيطين."], // TODO native review
 ["Clay Bomb","Bombe d'argile","قنبلة الطين"], // TODO native review
 ["Plants a proximity bomb.","Pose une bombe de proximité.","يزرع قنبلة تنفجر عند الاقتراب منها."], // TODO native review
 ["Shield Throw","Lancer de bouclier","رمية الدرع"], // TODO native review
 ["Throws a stone shield that ricochets.","Lance un bouclier de pierre qui ricoche.","يرمي درعا حجريا يرتد بين الأعداء."], // TODO native review
 ["Bodyguard","Garde du corps","حارس الجسد"], // TODO native review
 ["Reduces damage the hero takes while the tank is close.","Réduit les dégâts subis par le héros quand le tank est proche.","يقلل الضرر الذي يتلقاه البطل حين يكون الحارس قريبا."], // TODO native review
 ["Guardian Link","Lien du gardien","رابط الحارس"], // TODO native review
 ["The tank absorbs part of the damage the hero takes.","Le tank absorbe une partie des dégâts subis par le héros.","يمتص الحارس جزءا من الضرر الذي يتلقاه البطل."], // TODO native review
 ["Ambush","Embuscade","كمين"], // TODO native review
 ["Blinks to the top threat and strikes.","Se téléporte vers la menace principale et frappe.","ينتقل فورا إلى أخطر عدو ويضربه."], // TODO native review
 ["Execute","Exécution","إعدام"], // TODO native review
 ["Finishes weakened enemies.","Achève les ennemis affaiblis.","يقضي على الأعداء الضعفاء."], // TODO native review
 ["Venom Blade","Lame venimeuse","نصل السم"], // TODO native review
 ["Poisons the biggest threat.","Empoisonne la menace principale.","يسمم أخطر عدو."], // TODO native review
 ["Silencing Dart","Fléchette silencieuse","سهم الإسكات"], // TODO native review
 ["Shuts down ranged enemies.","Neutralise les attaques à distance des ennemis.","يعطل هجمات الأعداء بعيدة المدى."], // TODO native review
 ["Smoke Bomb","Bombe fumigène","قنبلة الدخان"], // TODO native review
 ["Throws smoke that blinds enemies.","Lance de la fumée qui aveugle les ennemis.","يلقي دخانا يعمي الأعداء."], // TODO native review
 ["Vanish","Disparition","اختفاء"], // TODO native review
 ["Makes the hero undetectable for a moment.","Rend le héros indétectable un instant.","يجعل البطل غير قابل للرصد للحظة."], // TODO native review
 ["Relentless Pursuit","Poursuite implacable","مطاردة لا هوادة فيها"], // TODO native review
 ["The assassin attacks much faster.","L’assassin attaque bien plus vite.","يهاجم القاتل بسرعة أكبر بكثير."], // TODO native review
 ["Bounty Contract","Contrat de prime","عقد المكافأة"], // TODO native review
 ["Enemies killed by the assassin drop extra cacao.","Les victimes de l’assassin lâchent plus de cacao.","الأعداء الذين يقتلهم القاتل يسقطون كاكاو إضافيا."], // TODO native review
 ["Might","Force","القوة"], // TODO native review
 ["Vigor","Vigueur","الحيوية"], // TODO native review
 ["Haste","Hâte","التسارع"], // TODO native review
 ["Reach","Portée","المدى"], // TODO native review
 ["Swiftness","Rapidité","السرعة"], // TODO native review
 ["Critical","Critique","الضربة الحرجة"], // TODO native review
 ["Armor","Armure","الدرع"], // TODO native review
 ["Renewal","Renouveau","التجدد"], // TODO native review
 ["Wisdom","Sagesse","الحكمة"], // TODO native review
 ["Fortune","Fortune","الثروة"], // TODO native review
 ["Smoking Mirror","Miroir de fumée","مرآة الدخان"], // TODO native review
 ["Ceiba Breath","Souffle du ceiba","نفس السيبا"], // TODO native review
 ["Blue Fire","Feu bleu","النار الزرقاء"], // TODO native review
 ["Ancestor Chorus","Chœur des ancêtres","جوقة الأسلاف"], // TODO native review
 ["Moon Tears","Larmes de lune","دموع القمر"], // TODO native review
 ["A smoking green star pierces through spirits.","Une étoile verte fumante transperce les esprits.","نجمة خضراء مدخنة تخترق الأرواح."], // TODO native review
 ["Jade beads orbit the shaman and burn the unquiet dead.","Des perles de jade entourent la chamane et brûlent les morts errants.","خرزات يشم تحيط بالساحرة وتحرق الموتى الهائمين."], // TODO native review
 ["Blue-green fire leaps from spirit to spirit.","Un feu bleu-vert bondit d’un esprit à l’autre.","نار زرقاء مخضرة تقفز من روح إلى أخرى."], // TODO native review
 ["A moonlit pool slows enemies and restores mana.","Un bassin lunaire ralentit les ennemis et rend du mana.","بركة مضاءة بالقمر تبطئ الأعداء وتستعيد المانا."], // TODO native review
 ["A rolling veil of copal smoke pushes enemies back.","Un voile de fumée de copal repousse les ennemis.","حجاب متدحرج من دخان الكوبال يدفع الأعداء للخلف."], // TODO native review
 ["Ancestral herbs restore health over a short moment.","Des herbes ancestrales rendent rapidement de la vie.","أعشاب الأسلاف تستعيد الصحة خلال لحظة قصيرة."], // TODO native review
 ["A dark mirror absorbs harm and returns mana.","Un miroir sombre absorbe les dégâts et rend du mana.","مرآة مظلمة تمتص الضرر وتعيد المانا."], // TODO native review
 ["A jade comet crosses the battlefield in a brilliant line.","Une comète de jade traverse le champ de bataille en ligne éclatante.","مذنب يشم يعبر ساحة القتال في خط متوهج."], // TODO native review
 ["Spectral cacao flowers erupt under nearby enemies.","Des fleurs de cacao spectrales éclatent sous les ennemis proches.","زهور كاكاو طيفية تتفجر تحت الأعداء القريبين."], // TODO native review
 ["A focused storm follows the densest enemy pack.","Une tempête suit le groupe d’ennemis le plus dense.","عاصفة مركزة تتبع أكثف مجموعة من الأعداء."], // TODO native review
 ["A luminous hummingbird spirit hunts on your behalf.","Un colibri spirituel lumineux chasse pour vous.","روح طائر طنان مضيئة تصطاد نيابة عنك."], // TODO native review
 ["A spectral serpent binds and crushes enemies who cross it.","Un serpent spectral entrave et écrase les ennemis qui le traversent.","أفعى طيفية تقيد الأعداء الذين يعبرونها وتسحقهم."], // TODO native review
 ["Fire a wheel of razor jade splinters.","Tirez une roue d’éclats de jade tranchants.","أطلق عجلة من شظايا اليشم الحادة."], // TODO native review
 ["The world tree exhales through the scepter.","L’arbre-monde souffle à travers le sceptre.","تنفث شجرة العالم أنفاسها عبر الصولجان."], // TODO native review
 ["Step through the spirit world, damaging foes on return.","Traversez le monde des esprits et blessez les ennemis à votre retour.","اعبر عالم الأرواح وألحق الضرر بالأعداء عند عودتك."], // TODO native review
 ["Four sacred bolts split toward the cardinal paths.","Quatre traits sacrés partent vers les points cardinaux.","أربعة مقذوفات مقدسة تنطلق في الاتجاهات الأصلية."], // TODO native review
 ["Cold ancestral flame blossoms around the caster.","Une flamme ancestrale froide fleurit autour de la mage.","لهب بارد من الأسلاف يزهر حول الساحرة."], // TODO native review
 ["Many voices answer at once, striking a long chain of foes.","Des voix réunies frappent une longue chaîne d’ennemis.","أصوات كثيرة تجيب معا وتضرب سلسلة طويلة من الأعداء."], // TODO native review
 ["Luminous drops fall in a crescent around your target.","Des gouttes lumineuses tombent en croissant autour de la cible.","قطرات مضيئة تهطل في هلال حول هدفك."], // TODO native review
 ["Wrap yourself in moonlight, gaining a ward and rapid mana recovery.","Drapez-vous de lune : un bouclier et une récupération rapide de mana.","تلفع بضوء القمر لتحصل على درع وتجدد سريع للمانا."], // TODO native review
];
