import test from 'node:test';
import assert from 'node:assert/strict';
import { compileAudio } from '../scripts/audio-catalog.mjs';
import { checkAudio } from '../scripts/check-audio.mjs';
import { ManifestAudio,resolveAudio,fallbackFile } from '../src/audio/ManifestAudio.js';
import { runAudioIds,bossAudioIds } from '../src/audio/runAudio.js';

const {catalog}=compileAudio();
class Param {constructor(){this.value=1;this.events=[];}setValueAtTime(v,t){this.value=v;this.events.push([v,t]);}setTargetAtTime(v,t){this.setValueAtTime(v,t);}linearRampToValueAtTime(v,t){this.events.push([v,t]);}cancelScheduledValues(){}}
class Node {constructor(ctx){this.ctx=ctx;this.gain=new Param();this.pan=new Param();this.playbackRate=new Param();}connect(){}disconnect(){this.disconnected=true;}start(time,offset=0){this.offset=offset;this.end=this.loop?Infinity:this.ctx.currentTime+this.buffer.duration-offset;this.ctx.sources.add(this);}stop(when=this.ctx.currentTime){this.end=when;if(when<=this.ctx.currentTime){this.ctx.sources.delete(this);this.onended?.();}}}
class Context {constructor(){this.currentTime=0;this.sources=new Set();this.destination={};}createGain(){return new Node(this);}createStereoPanner(){return new Node(this);}createBufferSource(){return new Node(this);}async decodeAudioData(){return {duration:12};}async resume(){}async close(){}advance(seconds){this.currentTime+=seconds;for(const source of [...this.sources])if(source.end<=this.currentTime){this.sources.delete(source);source.onended?.();}}}
function setup(present=true){const context=new Context(),warnings=[],fetches=[],save={data:{settings:{master:.8,music:.6,sfx:.7,ui:.5,ambience:.4,voice:.9,language:'en',voiceEnabled:true}}};
 const engine=new ManifestAudio(save,{catalog,available:present?Object.values(catalog).map(r=>r.file):[],contextFactory:()=>context,autoTick:false,warn:s=>warnings.push(s),random:()=>1,fetcher:async url=>{fetches.push(url);return {ok:true,arrayBuffer:async()=>new ArrayBuffer(1)};}});engine.unlock();return {engine,context,warnings,fetches,save};}

test('every manifest id resolves; generated code references are valid',()=>{for(const id of Object.keys(catalog))assert.equal(resolveAudio(id,catalog),id);assert.deepEqual(checkAudio().invalid,[]);assert.equal(checkAudio({references:[{id:'not-a-real-id'}]}).invalid.length,1);});
test('missing MP3 uses old WAV, warns once and caches decode',async()=>{const {engine,warnings,fetches,context}=setup(false);await engine.play('click');context.advance(.1);await engine.play('click');assert.equal(warnings.length,1);assert.deepEqual(fetches,['/assets/audio/sfx-click.wav']);assert.equal(fallbackFile('voice/ar/narration-2'),'narration/en-2.wav');engine.destroy();});
test('24 global effects, eight enemy voices, 60ms throttle, bounded pitch and positioning',async()=>{const {engine,context}=setup();const ids=Object.keys(catalog).filter(k=>k.startsWith('sfx/enemies/'));await Promise.all(ids.slice(0,12).map(id=>engine.play(id,{x:300,y:0})));assert.equal(engine.voices.size,8);await Promise.all(engine.group('ui').map(id=>engine.play(id)));assert.equal(engine.voices.size,24);const voice=[...engine.voices][0];assert.equal(voice.source.playbackRate.value,1.04);assert.equal(voice.panner.pan.value,.5);assert.equal(voice.gain.gain.value,.7);engine.stopOwner(undefined);assert.equal(engine.voices.size,0);context.advance(.1);assert.ok(await engine.play('click'));assert.equal(await engine.play('click'),false);context.advance(.061);assert.ok(await engine.play('click'));engine.destroy();});
test('category settings and nested music ducking release independently',async()=>{const {engine,save}=setup();engine.duck('cinematic',true);const voice=await engine.voice('boss-camazotz-entry');assert.ok(voice);assert.equal(await engine.voice('boss-zipacna-entry'),false);engine.duck('cinematic',false);assert.ok(Math.abs(engine.gains.music.gain.value-.6*Math.pow(10,-6/20))<1e-10);engine.stopVoice(voice);assert.equal(engine.gains.music.gain.value,.6);save.data.settings.voiceEnabled=false;engine.applySettings();assert.equal(engine.gains.voice.gain.value,0);assert.equal(engine.master.gain.value,.8);assert.equal(engine.gains.ui.gain.value,.5);assert.equal(await engine.voice('balam-select'),false);engine.destroy();});
test('localized voice and hero/run/boss lazy groups',async()=>{const {engine,save,fetches}=setup();save.data.settings.language='ar';await engine.voice('balam-select');assert.ok(fetches.at(-1).endsWith('/voice/ar/balam-select.mp3'));const ids=runAudioIds(engine,'balam','cenote','tank');assert.ok(ids.includes('music/map-cenote'));assert.ok(ids.includes('sfx/skills/jaguar-roar-cast'));assert.ok(!ids.includes('sfx/skills/copal-star-cast'));assert.ok(bossAudioIds(engine,'ahpuch').includes('voice/ar/boss-ahpuch-entry'));engine.destroy();});
test('music crossfades last four seconds, phase offsets, stop cancels transition',async()=>{const {engine,context}=setup();await engine.music('menu');assert.equal(engine.channels.get('music').nextAt,8);context.advance(7.9);engine.update();assert.equal(engine.voices.size,1);context.advance(.1);engine.update();assert.equal(engine.voices.size,2);context.advance(4);engine.update();assert.equal(engine.voices.size,1);await engine.music('boss-ahpuch',1.2,2);assert.equal(engine.channels.get('music').offset,4);assert.equal(engine.channels.get('music').end,8);await engine.channel('music',null,{fade:0});assert.equal(engine.channels.size,0);engine.destroy();assert.equal(context.sources.size,0);});
test('paused/destroyed owner prevents late async playback',async()=>{const {engine}=setup();const pending=engine.play('click',{owner:'run'});engine.pauseOwner('run');assert.equal(await pending,false);assert.equal(engine.voices.size,0);engine.resumeOwner('run');engine.destroy();assert.equal(await engine.play('hit'),false);});
test('stopping an ambience channel while decoding cancels late loops',async()=>{const {engine}=setup();const pending=engine.channel('weather','sfx/ambience/rain-light',{owner:'run'});engine.stopOwner('run');await pending;assert.equal(engine.voices.size,0);assert.equal(engine.channels.size,0);engine.destroy();});
test('preload cancellation and partial delivery stay safe',async()=>{const {engine,fetches}=setup();engine.available.delete('sfx/core/click.mp3');await engine.preload(['sfx/core/click','sfx/core/dart']);assert.ok(fetches.includes('/assets/audio/sfx-click.wav'));assert.ok(fetches.includes('/assets/audio-v06/sfx/core/dart.mp3'));const controller=new AbortController();controller.abort();await assert.rejects(engine.preload(['music/menu'],()=>{},controller.signal),{name:'AbortError'});engine.destroy();});
test('an old save gets safe category defaults, and phase one loops only its section',async()=>{const {engine,save}=setup();delete save.data.settings.voice;delete save.data.settings.ambience;delete save.data.settings.ui;engine.applySettings();assert.equal(engine.gains.voice.gain.value,.85);assert.equal(engine.gains.ambience.gain.value,.65);assert.equal(engine.gains.ui.gain.value,1);await engine.music('boss-ahpuch');assert.equal(engine.channels.get('music').offset,0);assert.equal(engine.channels.get('music').end,4);engine.destroy();});
for(const present of [false,true])test(`600-second audio simulation: ${present?'all present':'all missing'}`,async()=>{const {engine,context,warnings}=setup(present);const ids=engine.group('enemies');await engine.music('day');for(let second=0;second<600;second++){await Promise.all(ids.slice(second%10,second%10+10).map(id=>engine.play(id)));await engine.voice('announcer-level-up');context.advance(1);engine.update();assert.ok([...engine.voices].filter(v=>v.effect).length<=24);assert.ok([...engine.voices].filter(v=>v.enemy).length<=8);}assert.ok(engine.buffers.size<=Object.keys(catalog).length);assert.equal(new Set(warnings).size,warnings.length);engine.destroy();assert.equal(context.sources.size,0);});
